#!/usr/bin/env php
<?php
//////////
// Gron //
//////////

// Take valid JSON on stdin, then output it as discrete assignments to make it grep-able
// The code is hacky, but small.

// Tom Hudson - 2012
// https://github.com/TomNomNom/gron 

$buffer = file_get_contents('php://stdin');

$struct = json_decode($buffer);

printSruct($struct);

function printSruct($struct, $prefix = 'json'){
  if (is_object($struct)){
    echo "{$prefix} = {};\n";
  } elseif (is_array($struct)){
    echo "{$prefix} = [];\n";
  } else {
    echo "{$prefix} = ". json_encode($struct) .";\n";

    // No need to iterate if we already have a scalar
    return;
  }

  foreach ($struct as $k => $v){
    $k = json_encode($k);
    printSruct($v, "{$prefix}[{$k}]");
  }
}

