#!/bin/sh
PROJDIR=$(cd `dirname $0`/.. && pwd)
cd ${PROJDIR}

which gometalinter > /dev/null

if [ $? -ne 0 ]; then
    echo "You don't have gometalinter. Installing it..."
    go get github.com/alecthomas/gometalinter
    gometalinter --install
fi

# dupl is disabled because it has a habbit of identifying tests as duplicated code.
# in its defence: it's right. gocyclo is disabled because I'm a terrible programmer.
# gas is disabled because it doesn't like InsecureSkipVerify set to true for HTTP
# requests - but we only do that if the user asks for it.
gometalinter --disable=gocyclo --disable=dupl --enable=goimports --disable=gas
