#!/bin/bash
PROJDIR=$(cd `dirname $0`/.. && pwd)

TAG=${1}
USER="tomnomnom"
REPO="gron"

if [[ -z "${TAG}" ]]; then
    echo "Usage: ${0} <tag>"
    exit 1
fi

if [[ -z "${GITHUB_TOKEN}" ]]; then
    echo "You forgot to set your GITHUB_TOKEN"
    exit 2
fi

cd ${PROJDIR}
go build github.com/${USER}/${REPO}

github-release release \
    --user ${USER} \
    --repo ${REPO} \
    --tag ${TAG} \
    --name "${REPO} v${TAG}" \
    --description "v${TAG}" \
    --pre-release

github-release upload \
    --user ${USER} \
    --repo ${REPO} \
    --tag ${TAG} \
    --name "${REPO}-linux-amd64" \
    --file ${PROJDIR}/${REPO}
