#!/bin/bash
PROJDIR=$(cd `dirname $0`/.. && pwd)

TAG=${1}
USER="tomnomnom"
REPO="gron"
BINARY="${REPO}"
ARCHIVE="${BINARY}-linux-amd64-${TAG}.tgz"

if [[ -z "${TAG}" ]]; then
    echo "Usage: ${0} <tag>"
    exit 1
fi

if [[ -z "${GITHUB_TOKEN}" ]]; then
    echo "You forgot to set your GITHUB_TOKEN"
    exit 2
fi

cd ${PROJDIR}
go build github.com/${USER}/${REPO}
tar --create --gzip --file=${ARCHIVE} ${BINARY}

github-release release \
    --user ${USER} \
    --repo ${REPO} \
    --tag ${TAG} \
    --name "${REPO} v${TAG}" \
    --description "v${TAG}" \
    --pre-release

github-release upload \
    --user ${USER} \
    --repo ${REPO} \
    --tag ${TAG} \
    --name "${ARCHIVE}" \
    --file ${PROJDIR}/${ARCHIVE}
